
[metadata]
version = "0.0.1" # Opt
author = "OnyxTool" # Opt
description = "Dies ist ein Test!" # Opt

[globalConfig]
formulaFile = "formeln.toml" # Req!
inputDir = "Input"  # Opt def=Input
outputDir = "Output"# Opt def=Output
idOrdering = true   # Opt def=true

[[assessment]]
title = "System 1"            # Req
copyOf = "Vorlage 1"  # Req
# template = "Vorlage 1" # Opt def=null


[[assessment.image]]   # Opt
alt = "System"     # Opt def = ""
imgRef = "media/image1.png" # Req

[[assessment.var]]
id = "F"
set.random.upper = 100.0
set.random.lower = 10.0
set.random.places = 2

[[assessment.var]]
id = "L"
set.random.upper = 10.0
set.random.lower = 1.0
set.random.places = 2

[[assessment.var]]
id = "ERG_CODE_N1"
set.formula.id = "C1_N1"

[[assessment.var]]
id = "ERG_L_N1"
set.formula.id = "L1_N1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_N1"
set.formula.id = "R1_N1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_Q1"
set.formula.id = "C1_Q1"

[[assessment.var]]
id = "ERG_L_Q1"
set.formula.id = "L1_Q1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_Q1"
set.formula.id = "R1_Q1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_M1"
set.formula.id = "C1_M1"

[[assessment.var]]
id = "ERG_L_M1"
set.formula.id = "L1_M1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_M1"
set.formula.id = "R1_M1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_N2"
set.formula.id = "C1_N2"

[[assessment.var]]
id = "ERG_L_N2"
set.formula.id = "L1_N2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_N2"
set.formula.id = "R1_N2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_Q2"
set.formula.id = "C1_Q2"

[[assessment.var]]
id = "ERG_L_Q2"
set.formula.id = "L1_Q2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_Q2"
set.formula.id = "R1_Q2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_M2"
set.formula.id = "C1_M2"

[[assessment.var]]
id = "ERG_L_M2"
set.formula.id = "L1_M2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_M2"
set.formula.id = "R1_M2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_N3"
set.formula.id = "C1_N3"

[[assessment.var]]
id = "ERG_L_N3"
set.formula.id = "L1_N3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_N3"
set.formula.id = "R1_N3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_Q3"
set.formula.id = "C1_Q3"

[[assessment.var]]
id = "ERG_L_Q3"
set.formula.id = "L1_Q3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_Q3"
set.formula.id = "R1_Q3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_M3"
set.formula.id = "C1_M3"

[[assessment.var]]
id = "ERG_L_M3"
set.formula.id = "L1_M3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_M3"
set.formula.id = "R1_M3"
set.formula.mod.round.places = 2

[[assessment]]
title = "System 2"            # Req
copyOf = "Vorlage 1"

[[assessment.pre]]
id = "F" # Req
set.name.to = "M"
# set.<preprocessor>.<attributes>
# set.name
#         .to = "" #Req
#
#
[[assessment.image]]   # Opt
alt = "System"     # Opt def = ""
imgRef = "media/001.png" # Req

[[assessment.var]]
id = "M"
set.random.upper = 100.0
set.random.lower = 10.0
set.random.places = 2

[[assessment.var]]
id = "L"
set.random.upper = 10.0
set.random.lower = 1.0
set.random.places = 2

[[assessment.var]]
id = "ERG_CODE_N1"
set.formula.id = "C1_N1"

[[assessment.var]]
id = "ERG_L_N1"
set.formula.id = "L1_N1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_N1"
set.formula.id = "R1_N1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_Q1"
set.formula.id = "C1_Q1"

[[assessment.var]]
id = "ERG_L_Q1"
set.formula.id = "L1_Q1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_Q1"
set.formula.id = "R1_Q1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_M1"
set.formula.id = "C1_M1"

[[assessment.var]]
id = "ERG_L_M1"
set.formula.id = "L1_M1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_M1"
set.formula.id = "R1_M1"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_N2"
set.formula.id = "C1_N2"

[[assessment.var]]
id = "ERG_L_N2"
set.formula.id = "L1_N2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_N2"
set.formula.id = "R1_N2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_Q2"
set.formula.id = "C1_Q2"

[[assessment.var]]
id = "ERG_L_Q2"
set.formula.id = "L1_Q2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_Q2"
set.formula.id = "R1_Q2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_M2"
set.formula.id = "C1_M2"

[[assessment.var]]
id = "ERG_L_M2"
set.formula.id = "L1_M2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_M2"
set.formula.id = "R1_M2"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_N3"
set.formula.id = "C1_N3"

[[assessment.var]]
id = "ERG_L_N3"
set.formula.id = "L1_N3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_N3"
set.formula.id = "R1_N3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_Q3"
set.formula.id = "C1_Q3"

[[assessment.var]]
id = "ERG_L_Q3"
set.formula.id = "L1_Q3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_Q3"
set.formula.id = "R1_Q3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_CODE_M3"
set.formula.id = "C1_M3"

[[assessment.var]]
id = "ERG_L_M3"
set.formula.id = "L1_M3"
set.formula.mod.round.places = 2

[[assessment.var]]
id = "ERG_R_M3"
set.formula.id = "R1_M3"
set.formula.mod.round.places = 2