= Über JQTI+

JQTI+ ist die Bibliothek, um Daten im QTI v2.1 Standard abgespeichert sind, in ein DOM Modell zu überführen.
Allerdings wurde die Bibliothek zuletzt im Jahr 2018 angerührt, allerdings ist sie hinreichend umfangreich.

== Das Parsen von `.xml` Dateien.

Um XML Dateien in ein Objektmodell zu überführen, bedarf es einem speziellen ablauf:

=== Mittels *Facade*

Die Bibliothek bietet eine Facade an, die einem das parsen Erleichtert.

[source,java]
----
SimpleJqtiFacade facade = new SimpleJqtiFacade(); // <1>
// Nun kommt die vorbereitung zum parsen.
ResourceLocator locator = new FileResourceLocator(); // <2>
URI uri = new File("name.xml").toURI(); // <3>
boolean schemaValidation = false; // <4>

// Nun das überführen in ein DOM modell.
QtiObjectReadResult<AssessmentTest> objectResult = facade.readQtiRootNode(
        locator,
        uri,
        schemaValidation,
        AssessmentTest.class
); // <5>
----
<1> Die Facade zum Parsen
<2> Der ResourcenLocator, stellt sicher dass die Daten auch wirklich da sind.
<3> Die URI der Resource, über die File Schnittstelle lässt sich das sehr angenehm lösen.
<4> Ob der Parser das XML Schema überprüfen soll.
<5> Der aufruf der Methode `readQtiRootNode()` der Facade, mit den entsprechenden Parametern

Diese Methode nimmt einem einen großteil der Arbeit ab.
Man muss im vorhinein Wissen, welche Klasse diese Datei sein soll.

Für uns Interessant sind da die Klassen:

- `AssessmentTest`
- `AssessmentItem`

Um die `rootNode` der jeweiligen Klassen aus dem `objectResult` zu extrahieren, muss die Methode `getRootNode()` benutzt werden.

Ab da traversiert man die XML Struktur.

=== Manuell

Siehe implementierung der Facade link:https://github.com/davemckain/qtiworks/blob/2d8c502d8f2b266fd80197ad19bcae3d4566276a/qtiworks-jqtiplus/src/main/java/uk/ac/ed/ph/jqtiplus/SimpleJqtiFacade.java[`SimpleJqtiFacade.java`]

// TODO Codebeispiel

== Das Erstellen von XML Dateien aus dem DOM Modell.

=== Mittels `QtiSerializer`

Die Klasse QtiSerializer ermöglicht das einfache serialisieren in XML Dateien mittels gängiger Methoden.
Siehe link:https://github.com/davemckain/qtiworks/blob/2d8c502d8f2b266fd80197ad19bcae3d4566276a/qtiworks-jqtiplus/src/main/java/uk/ac/ed/ph/jqtiplus/serialization/QtiSerializer.java[`QtiSerializer.java`].

// TODO Codebeispiel